### ISSUE TITLE
Make wx.adv.TaskBarIcon not the only option, or at least not default

### ISSUE THREAD

**Issue by guysoft** [guysoft/backupfriend-client#8]
Getting reports that the icon is sitting in a strange way on OSX, and that it does not appear at all on GNOME desktop running Pop!_OS.

This is strange,  that is GNOME desktop, and wxpython uses gtk. It says so here too:
https://wxpython.org/Phoenix/docs/html/wx.adv.TaskBarIcon.html

What we could do is have an option to "minimize to systray" and now have that on the first boot.

**Comment by gabay** [comment]
The problem on my machine is caused by Gnome3 not accepting taskbar icons by default
To fix - the user must install this tray icons gnome extension: https://extensions.gnome.org/extension/1503/tray-icons/

We can check if the taskbar is available using `wx.adv.TaskBarIcon.IsAvailable()` (On my machine, it returns `True`/`False` when the extension is enabled/disabled, respectively)

**Comment by guysoft** [comment]
Ok, it seems like making a dialog pop up testing ``wx.adv.TaskBarIcon.IsAvailable()`` and stating if its missing is a good current solution.

**Comment by guysoft** [comment]
Tested and works on Mac Windows and Linux
